services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - "../data/mysql-data:/var/lib/mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  python:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "../api:/app"
    ports:
      - "8000:8000"